### ISSUE TITLE
Fix "could not find function "aes" error on Cluster Membership olot

### ISSUE THREAD

**Issue by nsh87** [nsh87/receptormarker#71]
Need to fix error caused by using `ggplot` instead of `ggplot2` in f21e6091bb7c3c9681f47f21d6e14d9eae8525ba.

**Comment by nsh87** [comment]
![screen shot 2016-07-09 at 2 24 37 pm](https://cloud.githubusercontent.com/assets/4327717/16710384/e54549aa-45e0-11e6-8e82-504f15fdfc36.png)

**Comment by nsh87** [comment]
@catterbu: we have to get more rigorous about testing...

**Comment by nsh87** [comment]
I think this is why... but investigating.

**Comment by nsh87** [comment]
@catterbu: when you're working w/ the package or testing, make sure you haven't done `library(ggplot2)` or any other package dependencies. looks like you had ggplot2 loaded in your local R so you weren't seeing this error, but `aes` and `element_blank()` needed to be referenced explicitly as being from `ggplot2`.

**Comment by catterbu** [comment]
That was precisely the problem. I think we should have tests for each plot that just check for errors or not if plotted. I cannot recall of that is there. Sorry about the bugs. Because of the limited time I guess I shortcut a few things. Will endeavor to be better in the future. :)

**Comment by nsh87** [comment]
No worries. Ya, we had tried the plotting thing...It's a good idea. I 
remember the issue was that kmeans is random and we didn't realize the seed 
was changing so the results were changing...
